### PR TITLE
Create GS-GXP1630.sample

### PR DESCRIPTION
**Pull request by Abe-Telo**
A template that was directly downloaded from GXP1630. 
Please modify the default template as you wish to implement. 

 
Grandstream Template Sample to add into your DB

### CODE REVIEW

**Comment by Stell0** [comment]
Hi @Abe-Telo, thank you for submitting this pull request. Sadly I'm not able to test anything about this phone, so you'll have to do all the work by yourself to make it work with Tancredi. BTW I can help you to make things work.
- First of all, here you can find the documentation https://nethesis.github.io/tancredi/templates/

You'll need to add a regular expression that will match the pattern of the file that the phone will request. Usually the configuration file has the MAC address in it, this regular expression is used to find the scope when the file is requested without the token
https://nethesis.github.io/tancredi/templates/#templaterequest-binding-the-patternsd-directory [here](https://github.com/nethesis/tancredi/tree/master/data/patterns.d) you can find the patterns of other brands

Than you need to create the template file. You can take your sample file and use the [Twig 1 syntax](https://twig.symfony.com/doc/1.x/)
The list of the variables that you can use into your scope file and template is [here](https://nethesis.github.io/tancredi/variables/)

Then you have to create a scope file for each model. Scope file is a .ini like [those](https://github.com/nethesis/tancredi/tree/master/data/scopes). In scope file you can define all the default  variables of the phone that differs from the default.ini scope.

If you try to scaffold those files, I can help you tweaking them to have something that you can test

**Comment by gsanchietti** [comment]
I think we can close this one @Stell0

**Comment by Abe-Telo** [comment]
Sending this to my work email ***@***.*** moving forward will
communicate from there.

I will look into this tomorrow and get back to you for more information in
the next few days.

**Comment by Abe-Telo** [comment]
Hi again. and sorry for taking this long, i wanted to recap, I just ran a fresh install, to see if i can go anywhere with this. but this is what i am getting. This is a test server and all files is open and unsecured during this test. Additionally i am leaving my config thats in the etc/tancredi.conf in the main root to be able to review it.  66.228.47.155/tancredi/ 

I also noticed. That no change is updating when i change this from the etc/tancredi.conf. in ubunto 

image

**Pull request closed without merging**
